[WIP]Feat/filter tag
alfa-laboratory/core-components pull request #1035
Opened 2022-03-21 15:26 UTC by EGNKupava

2022-03-23 16:31 UTC, SiebenSieben commented on packages/filter-tag/src/index.module.css
> +            min-width: 84px;
Минимальная ширина только когда checked?

2022-03-23 16:33 UTC, SiebenSieben commented on packages/filter-tag/src/index.module.css
> +        outline: 2px solid var(--color-light-border-link);
Есть миксин focus-outline

2022-03-23 20:32 UTC, EGNKupava commented on packages/filter-tag/src/index.module.css
> +            min-width: 84px;
В обычном состоянии min-width берется от тега

2022-03-24 14:17 UTC, reme3d2y requested changes

2022-03-24 14:17 UTC, reme3d2y commented on packages/filter-tag/src/docs/description.mdx
> +            onClick={() => setChecked(true)}
надо бы open добавить

2022-03-24 14:17 UTC, reme3d2y commented on packages/filter-tag/src/index.module.css
> +.xxs {
Это чтобы от тэга стили перебить?

nit: Можно объединить в один селектор. И стоит добавить коммент, чтобы кто-то случайно это не удалил

2022-03-24 14:17 UTC, reme3d2y commented on packages/filter-tag/src/index.module.css
> +    &.default {
по возможности стоит модификаторы и элементы располагать отдельно, а не вкладывать внутрь. Иначе через className будет невозможно переопределить некоторые свойства

2022-03-24 14:17 UTC, reme3d2y commented on packages/intl-phone-input/src/component.tsx
> +                optionsListWidth='field'
а это откуда залетело?

2022-03-25 08:26 UTC, EGNKupava commented on packages/intl-phone-input/src/component.tsx
> +                optionsListWidth='field'
хз/ Меняю назад, а гит не понимает.. Ну надо с одинарными ковычками)

2022-03-25 09:31 UTC, SiebenSieben approved these changes

2022-03-25 13:12 UTC, blackraydev approved these changes

2022-03-26 05:44 UTC, reme3d2y commented on packages/filter-tag/src/index.module.css
> +        & > span {
Почему так решил сделать? Можно ведь оставить 24х24 и поменять паддинг в 272й?

2022-03-26 05:44 UTC, reme3d2y commented on packages/filter-tag/src/index.module.css
> +        left: 0;
Не помню уже где, но где-то точно такое неявное центрирование не работает.

Лучше явно добавить top: 50%, translateY(-50%)

2022-03-26 05:44 UTC, reme3d2y commented on packages/filter-tag/src/index.module.css
> +    overflow: hidden;
Есть проблемка с фокусной рамкой у крестика. Можно тут убрать     overflow: hidden; и добавить border-radius'ы для кнопок, то должно быть все ок

2022-03-26 05:44 UTC, reme3d2y commented on packages/tag/src/default.module.css
> -
давай из inverted тоже вынесем цвета тогда

2022-03-28 07:24 UTC, EGNKupava commented on packages/filter-tag/src/index.module.css
> +        & > span {
Ок, поменял

2022-03-28 07:39 UTC, Oladii approved these changes

2022-03-28 13:17 UTC, merged