feat(modal): add modal
alfa-laboratory/core-components pull request #412
Opened 2020-12-07 17:20 UTC by xchaikax

Добавляет компонент `Modal`.
Также включает вспомогательные компоненты `TrapFocus` и `Fade`.
Portal отредактирован в соответствии с требованиями `Modal`.
За основу взято решение из `newclick-components` +  накоторые решения из `arui-feather`. 
Closes #348

2020-12-14 09:06 UTC, reme3d2y commented
ПР уже можно смотреть или это драфт?
Очень сложно сейчас отревьювить:

1. Не стоит вносить лишние изменения в имеющиеся компоненты, особенно мажорные. Это можно сделать в отдельном ПР и то, если в этом есть необходимость.
2. Много копипасты. Это плохо, т.к. потом может оказаться, что никто в деталях не знает, как работает компонент.
3. Вместо useForkRef и setRef стоит заюзать mergeRefs, который используется во всех других компонентах. Не стоит плодить решения, потом будет сложнее рефакторить и поддерживать
4. ModalManager в этом ПР нигде не используется. Лучше принести это в отдельном ПР.
5. В css нарушено соглашение по неймингу переменных (сами названия и kebab-case)
6. Что по стилям?
7. Имеет ли смысл иметь Fade отдельно от модалки, это ведь просто обвязка над Transition? К тому же есть CSSTransition для этих целей 
8. В других компонентах дочерние лежат в папке components. Предлагаю придерживаться единообразия

2020-12-15 11:11 UTC, xchaikax commented
> 1. Не стоит вносить лишние изменения в имеющиеся компоненты, особенно мажорные. Это можно сделать в отдельном ПР и то, если в этом есть необходимость.
Принял, попробую перенести на текущий портал или минимально отредактировать его. Для работы этой модалки (брал из ньюклика и частично менял ее) портал точно должен принимать реф. 
> 3. Вместо useForkRef и setRef стоит заюзать mergeRefs, который используется во всех других компонентах. Не стоит плодить решения, потом будет сложнее рефакторить и поддерживать
Про mergeRefs понял, setRef думаю может пригодиться, можно его потом в alfalab/utils вынести
> 4. ModalManager в этом ПР нигде не используется. Лучше принести это в отдельном ПР.
Менеджер используется для контроля модалок, в том числе для вызова нескольких сразу или одной из другой. используется как defaultManager в пропе manager модалки. 
> 5. В css нарушено соглашение по неймингу переменных (сами названия и kebab-case)
> 6. Что по стилям?
Где можно побольше почитать?
> 7. Имеет ли смысл иметь Fade отдельно от модалки, это ведь просто обвязка над Transition? К тому же есть CSSTransition для этих целей
> 8. В других компонентах дочерние лежат в папке components. Предлагаю придерживаться единообразия
Понял, приведу в общий вид. fade, backdrop и trapfocus занесу в компоненты

2020-12-24 08:20 UTC, reme3d2y commented
Дизайнеры хотят прокачивать модалку — нужно будет постоянно вносить изменения. Поэтому хочется, чтобы код был максимально простым и понятным и чтобы хотя бы кто-то знал в нем каждую строчку. Сейчас очень много заимствований из других либ, что не ок. Иначе мы на чужие требования и костыли накинем еще и свои и будет вообще не очень))

> Принял, попробую перенести на текущий портал или минимально отредактировать его. Для работы этой модалки (брал из ньюклика и частично менял ее) портал точно должен принимать реф.

Нужно подогнать код модалки под текущую реализацию. 

> Про mergeRefs понял, setRef думаю может пригодиться, можно его потом в alfalab/utils вынести

Давай setRef уберем. Не вижу, чтобы он был нужен.

> Менеджер используется для контроля модалок, в том числе для вызова нескольких сразу или одной из другой. используется как defaultManager в пропе manager модалки.

В фижере нет менеджера и норм. Предлагаю не вносить лишнюю функциональность. Появится запрос — обсудим отдельно и добавим

> Где можно побольше почитать?

Можно ориентироваться на текущие компоненты

> Понял, приведу в общий вид. fade, backdrop и trapfocus занесу в компоненты

fade и backdrop можно прикопать модалке
А trapfocus можно в отдельный компонент (пакет)

2020-12-24 08:21 UTC, reme3d2y requested changes
Дизайнеры хотят прокачивать модалку — нужно будет постоянно вносить изменения. Поэтому хочется, чтобы код был максимально простым и понятным и чтобы хотя бы кто-то знал в нем каждую строчку. Сейчас очень много заимствований из других либ, что не ок. Иначе мы на чужие требования и костыли накинем еще и свои и будет вообще не очень))

Принял, попробую перенести на текущий портал или минимально отредактировать его. Для работы этой модалки (брал из ньюклика и частично менял ее) портал точно должен принимать реф.

Нужно подогнать код модалки под текущую реализацию.

Про mergeRefs понял, setRef думаю может пригодиться, можно его потом в alfalab/utils вынести

Давай setRef уберем. Не вижу, чтобы он был нужен.

Менеджер используется для контроля модалок, в том числе для вызова нескольких сразу или одной из другой. используется как defaultManager в пропе manager модалки.

В фижере нет менеджера и норм. Предлагаю не вносить лишнюю функциональность. Появится запрос — обсудим отдельно и добавим

Где можно побольше почитать?

Можно ориентироваться на текущие компоненты

Понял, приведу в общий вид. fade, backdrop и trapfocus занесу в компоненты

fade и backdrop можно прикопать модалке
А trapfocus можно в отдельный компонент (пакет)

2020-12-30 06:53 UTC, SiebenSieben commented
Думаю, можно мёрджить. Отдельным реквестом докрутим.

Я бы пока убрал <Story>, чтобы скрыть в сторибуке и никого не смущать.

2020-12-30 09:27 UTC, merged