feat(collapse): add collapse component
alfa-laboratory/core-components pull request #439
Opened 2020-12-21 14:14 UTC by redzumi

# Опишите проблему
Компонент «подката» позволяет спрятать кусок текста за ссылку «Еще...».

# Чек лист
- [ ] Тесты
- [ ] Документация

# Дополнительная информация
https://digital.alfabank.ru/components/collapse

2020-12-21 15:47 UTC, dmitrsavk requested changes

2020-12-21 15:47 UTC, dmitrsavk commented on packages/collapse/package.json
> +  "version": "0.0.1",
мы обычно ставим версию 1.0.0

2020-12-21 15:47 UTC, dmitrsavk commented on packages/collapse/src/Component.test.tsx
> +            expect(render(<Collapse>{paragraph}</Collapse>)).toMatchSnapshot();
лучше делать снэпшот так:
```tsx
const { container } = render(<Collapse>{paragraph}</Collapse>);

expect(container).toMatchSnapshot();
```

так будет меньше мусора в снэпшоте

2020-12-21 15:47 UTC, dmitrsavk commented on packages/collapse/src/Component.tsx
> +import { ArrowDownSBlackIcon, ArrowUpSBlackIcon } from '@alfalab/icons-classic';
лучше импортирвать иконки не из индексного файла:
```tsx
import { ArrowDownSBlackIcon } from '@alfalab/icons-classic/ArrowDownSBlackIcon';
import { ArrowUpSBlackIcon } from '@alfalab/icons-classic/ArrowUpSBlackIcon';
```
а то на некоторых проектах лишние иконки в бандл залетают

2020-12-21 15:47 UTC, dmitrsavk commented on packages/collapse/src/Component.tsx
> +    isExpanded?: boolean;
может лучше просто `expanded`?

2020-12-21 15:47 UTC, dmitrsavk commented on packages/collapse/src/Component.tsx
> +    'data-test-id'?: string;
мы используем `dataTestId`

2020-12-21 15:47 UTC, dmitrsavk commented on packages/collapse/src/Component.tsx
> +export const Collapse = (props: CollapseProps) => {
можно добавить `forwardRef`

2020-12-21 15:47 UTC, dmitrsavk commented on packages/collapse/src/Component.tsx
> +export default Collapse;
а зачем еще и `export default`?

2020-12-21 15:47 UTC, dmitrsavk commented on packages/collapse/src/Component.tsx
> +        if (!isClient) return;
разве эффекты вызываются на сервере?

2020-12-21 15:47 UTC, dmitrsavk commented on packages/collapse/src/Component.tsx
> +        setExpanded(!expanded);
тут лучше будет так:
```tsx
setExpanded(value => !value)
```

2020-12-21 15:47 UTC, dmitrsavk commented on packages/collapse/src/Component.tsx
> +    const handleExpandedChange = () => {
лучше завернуть в `useCallback`

2020-12-21 15:47 UTC, dmitrsavk commented on packages/collapse/src/Component.tsx
> +        <div className={`${className} ${styles.collapse}`} id={id} data-test-id={dataTestId}>
заюзай лучше `classnames`

2020-12-21 15:47 UTC, dmitrsavk commented on packages/collapse/src/index.module.css
> +    outline: none;
если скрываем `outline`, то наверное надо еще заюзать хук `useFocus`
пример можешь посмотреть в кнопке

2020-12-22 11:30 UTC, redzumi commented on packages/collapse/src/Component.tsx
> +        setExpanded(!expanded);
а, собственно, зачем?)

2020-12-22 11:39 UTC, redzumi commented
@dmitrsavk поправил, спасибо!)

2020-12-22 12:12 UTC, dmitrsavk commented on packages/collapse/src/Component.tsx
> +        setExpanded(!expanded);
в данном случае это не обязательно, но иногда ловил баг из-за этого

2020-12-22 12:18 UTC, dmitrsavk commented on packages/collapse/src/Component.stories.mdx
> +Компонент для установки расстояния между компонентами.
описание от другого компонента)

2020-12-22 12:18 UTC, dmitrsavk commented on packages/collapse/src/Component.tsx
> +        // eslint-disable-next-line consistent-return
уже можно не отключать линтер)

2020-12-22 12:18 UTC, dmitrsavk approved these changes

2020-12-22 12:43 UTC, redzumi commented on packages/collapse/src/Component.tsx
> +        // eslint-disable-next-line consistent-return
точно точно)

2020-12-24 14:19 UTC, Luchanso approved these changes

2020-12-28 12:51 UTC, SiebenSieben commented on packages/collapse/src/Component.tsx
> +                <ToggledIcon className={styles.icon} />
Иконку нужно в слот (rightAddons), чтобы подчёркивание было только под текстом

2020-12-28 13:02 UTC, redzumi commented
@SiebenSieben привет, спасибо, все поправил)

2020-12-28 15:28 UTC, SiebenSieben approved these changes

2020-12-29 09:18 UTC, reme3d2y approved these changes

2020-12-29 16:07 UTC, merged