feat(toast): add component
alfa-laboratory/core-components pull request #478
Opened 2021-01-19 14:24 UTC by dmitrsavk

2021-01-25 05:17 UTC, SiebenSieben commented
Анимация scale нужна и у тултипа, может в отдельном реквесте?

2021-01-26 13:40 UTC, Artess999 commented
В Notification сломалась иконка warning и, кажется, поехало выравнивание заголовка
<img width="486" alt="Снимок экрана 2021-01-26 в 16 38 57" src="https://user-images.githubusercontent.com/25062433/105852169-2ce89b80-5ff5-11eb-89f4-838277730105.png">
<img width="460" alt="Снимок экрана 2021-01-26 в 16 38 49" src="https://user-images.githubusercontent.com/25062433/105852172-2eb25f00-5ff5-11eb-821c-7b9c4c23a524.png">

2021-01-27 15:25 UTC, SiebenSieben commented
Чуть прыгает с текстом:
![toast](https://user-images.githubusercontent.com/109410/106012921-fd0cc700-60cc-11eb-9536-a49d016df535.gif)

2021-01-27 15:48 UTC, dmitrsavk commented
> Чуть прыгает с текстом:
Это потому что если текста нет (children), то выравнивается по середине

2021-01-28 08:02 UTC, aso1datov commented on packages/popover/src/Component.tsx
> +    transition = { timeout: TRANSITION_DURATION },
nit: можно вынести за компонент и передавать ссылку

2021-01-28 08:03 UTC, aso1datov commented on packages/popover/src/Component.tsx
> +                    classNames={{
nit: можно вынести за компонент и передавать ссылку

2021-01-28 08:10 UTC, aso1datov commented on packages/themes/src/mixins/button/default-inverted.css
> +    --color-light-text-primary-inverted: #fff;
```suggestion
    --color-light-text-primary-inverted: var(--color-white);
```

2021-01-28 08:17 UTC, aso1datov commented on packages/toast-plate/src/component.tsx
> +                            {leftAddons ||
Тут точно не должно быть вот так вот:

```
(leftAddons || badge) && (
            <Badge
              view="icon"
              content={iconComponents[badge]}
              iconColor={badge}
              className={styles.badge}
            />
          )
```

2021-01-28 08:18 UTC, aso1datov commented on packages/toast-plate/src/component.tsx
> +    leftAddons?: ReactNode;
nit: почему во множественном числе?

2021-01-28 10:53 UTC, SiebenSieben commented
> > Чуть прыгает с текстом
> 
> Это потому что если текста нет (children), то выравнивается по середине

Так дизайнеры докопаются )

Позиция иконки относительно заголовка и экшн-кнопки относительно крестика не должна зависеть от наличия текста

2021-01-28 19:33 UTC, Artess999 commented
ломается, если отсутствует бейдж в Notification
<img width="426" alt="Снимок экрана 2021-01-28 в 22 32 20" src="https://user-images.githubusercontent.com/25062433/106189000-c2805880-61b8-11eb-9bf4-39079dff9538.png">

2021-01-29 10:17 UTC, SiebenSieben approved these changes

2021-02-01 05:47 UTC, reme3d2y requested changes

2021-02-01 05:47 UTC, reme3d2y commented on bin/purgecss.sh
> +    --ignore @alfalab/core-components-toast-plate \
Вроде же игнора в  bin/purgecss.js достаточно должно быть?

2021-02-01 05:47 UTC, reme3d2y commented on packages/notification/package.json
>          "@alfalab/core-components-button": "^1.11.0",
button можно удалить

2021-02-01 05:47 UTC, reme3d2y commented on packages/notification/tsconfig.json
> +    "references": [{ "path": "../button" }, { "path": "../portal" }, { "path": "../toast-plate" }]
button можно удалить

2021-02-01 05:47 UTC, reme3d2y commented on packages/popover/src/Component.tsx
> +                    classNames={CSS_TRANSITION_CLASS_NAMES}
можно просто styles сюда закинуть)

2021-02-01 05:47 UTC, reme3d2y commented on packages/toast-plate/src/component.tsx
> +                                {leftAddons ||
Немного запутанно выглядит

2021-02-01 05:47 UTC, reme3d2y commented on packages/toast-plate/src/component.tsx
> +                            {actionButton || null}
почему тут так?

2021-02-01 05:47 UTC, reme3d2y commented on packages/toast-plate/src/index.module.css
> +    min-height: 56px;
кажется, что пора эти значения вынести в общие переменные

2021-02-01 05:47 UTC, reme3d2y commented on packages/toast/package.json
> +        "react-transition-group": "^4.3.0"
react-merge-refs потерялся

2021-02-01 05:47 UTC, reme3d2y commented on packages/toast/src/component.tsx
> +        centeredPosition?: boolean;
не очень нравится название — не сразу понятно, по горизонтали или вертикали. А если по горизонтали нужно?

2021-02-01 05:47 UTC, reme3d2y commented on packages/toast/src/component.tsx
> +                        {...callbacks}
может все остальные общие свойства тоже собрать вместе?

2021-02-01 07:58 UTC, dmitrsavk commented on bin/purgecss.sh
> +    --ignore @alfalab/core-components-toast-plate \
нет

2021-02-01 07:59 UTC, dmitrsavk commented on packages/popover/src/Component.tsx
> +                    classNames={CSS_TRANSITION_CLASS_NAMES}
лучше явно указать

2021-02-01 08:03 UTC, dmitrsavk commented on packages/toast-plate/src/component.tsx
> +                                {leftAddons ||
взял из Notification, поправил

2021-02-01 08:05 UTC, reme3d2y commented on packages/popover/src/Component.tsx
> +                    classNames={CSS_TRANSITION_CLASS_NAMES}
🤷
```
classNames={styles}
```
прикольнее выглядит)

2021-02-01 08:07 UTC, dmitrsavk commented on packages/toast-plate/src/component.tsx
> +                            {actionButton || null}
поправил

2021-02-01 08:09 UTC, dmitrsavk commented on packages/toast/src/component.tsx
> +        centeredPosition?: boolean;
как предлагаешь?

2021-02-01 08:21 UTC, reme3d2y commented on packages/toast/src/component.tsx
> +        centeredPosition?: boolean;
а есть кейсы, когда должно быть не по центру? 

т.е. кажется, что либо должно быть всегда по центру + block=true|false, либо тогда 'left' | 'center' | 'right' и block=true|false

2021-02-01 08:22 UTC, reme3d2y approved these changes

2021-02-01 08:53 UTC, dmitrsavk commented on packages/toast/src/component.tsx
> +        centeredPosition?: boolean;
эту пропсу я добавил, чтобы можно было реализовать кейс Клика, когда тост рендерится в произвольный контейнер и у него не должно быть никаких смещений

2021-02-08 06:57 UTC, SiebenSieben commented on packages/toast/src/component.tsx
> +        centeredPosition?: boolean;
Так может bottomCenteredPosition?

2021-02-08 14:41 UTC, merged

2021-02-08 15:02 UTC, dmitrsavk commented
:tada: This PR is included in version 9.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@alfalab/core-components/v/9.0.0)
- [GitHub release](https://github.com/alfa-laboratory/core-components/releases/tag/v9.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: