feat(collapse): add ability to change state using prop expanded
alfa-laboratory/core-components pull request #659
Opened 2021-05-17 06:08 UTC by avlnche64

добавил возможность управлять состоянием компонента снаружи

2021-05-19 08:12 UTC, SiebenSieben commented on packages/collapse/src/index.module.css
> +    margin-top: 15px;
Ох уж эти депрекейтед 15px из фижера ) поправим отдельно

2021-05-21 06:24 UTC, dmitrsavk approved these changes

2021-05-25 07:53 UTC, reme3d2y requested changes

2021-05-25 07:53 UTC, reme3d2y commented on packages/collapse/src/Component.tsx
> +    useEffect(() => {
В таком подходе смешивается controlled и uncontrolled подход.
Например, вот такой кейс будет работать неправильно:

![image](https://user-images.githubusercontent.com/9968618/119458694-b1e68600-bd45-11eb-9609-52c2b1db5d06.png)

Предлагаю заменить на 
```tsx
const uncontrolled = expanded === undefined; // компонент управляется изнутри
const [expandedState, setExpandedState] = useState(expanded);
const isExpanded = uncontrolled ? expandedState : expanded;

const handleExpandedChange = useCallback(() => {
    if (uncontrolled) {
        // Меняем состояние только если компонент не управляется снаружи
        setExpandedState(!isExpanded);
    }

    if (onExpandedChange) onExpandedChange();
}, [isExpanded, onExpandedChange, uncontrolled]);
```  

Либо сделать компонент полностью controlled.

2021-05-25 07:53 UTC, reme3d2y commented on packages/collapse/src/Component.tsx
> +    useEffect(() => {
Сорри за долгое ревью :(

2021-05-25 09:42 UTC, merged

2021-05-25 10:12 UTC, dmitrsavk commented
:tada: This PR is included in version 16.5.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@alfalab/core-components/v/16.5.0)
- [GitHub release](https://github.com/alfa-laboratory/core-components/releases/tag/v16.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: