feat(calendar-range): pass props to render calendar in popper
alfa-laboratory/core-components pull request #702
Opened 2021-06-16 12:45 UTC by koretskyhub

Передает пропсы для отрисовки календарей в поповере и правит отступ правого календаря

2021-06-17 06:20 UTC, reme3d2y commented on packages/calendar-range/src/Component.tsx
> +                calendarPosition={(inputFromProps && inputFromProps.calendarPosition) || 'static'}
Может лучше добавим calendarPosition в пропсы CalendarRange. Думаю так удобнее будет, т.к. это часто используемая опция будет. 

И там ниже скриншот от селекта попал

2021-06-21 07:13 UTC, koretskyhub commented on packages/calendar-range/src/Component.tsx
> +                calendarPosition={(inputFromProps && inputFromProps.calendarPosition) || 'static'}
done

2021-06-21 07:25 UTC, SiebenSieben approved these changes

2021-06-21 12:19 UTC, dmitrsavk approved these changes

2021-06-28 13:44 UTC, reme3d2y requested changes
Нужно бы тестов накинуть
У меня вот такой [кейс](https://alfa-laboratory.github.io/core-components/86db70d22dc2f2f2fa1c38ffbaff3f6d665007c0/?path=/docs/%D0%B3%D0%B0%D0%B9%D0%B4%D0%BB%D0%B0%D0%B9%D0%BD%D1%8B-%D0%BF%D0%B5%D1%81%D0%BE%D1%87%D0%BD%D0%B8%D1%86%D0%B0--page/code=function%20Example()%20%7B%0A%20%20const%20defaultDate%20%3D%20%2230.06.2021%22%3B%0A%20%20const%20%5BvalueFrom%2C%20setValueFrom%5D%20%3D%20React.useState(defaultDate)%3B%0A%20%20const%20%5BvalueTo%2C%20setValueTo%5D%20%3D%20React.useState(%22%22)%3B%0A%20%20const%20minDate%20%3D%20(new%20Date().getTime())%20-%205%20*%2024%20*%2060%20*%2060%20*%201000%3B%0A%20%20const%20maxDate%20%3D%20(new%20Date().getTime())%20%2B%205%20*%2024%20*%2060%20*%2060%20*%201000%3B%0A%20%20%0A%20%20return%20(%0A%20%20%20%20%20%20%3CCalendarRange%0A%20%20%20%20%20%20%20%20%20%20minDate%3D%7BminDate%7D%0A%20%20%20%20%20%20%20%20%20%20maxDate%3D%7BmaxDate%7D%0A%20%20%20%20%20%20%20%20%20%20valueFrom%3D%7BvalueFrom%7D%0A%20%20%20%20%20%20%20%20%20%20valueTo%3D%7BvalueTo%7D%0A%20%20%20%20%20%20%20%20%20%20onDateFromChange%3D%7B(%7B%20value%20%7D)%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20setValueFrom(value)%3B%0A%20%20%20%20%20%20%20%20%20%20%7D%7D%0A%20%20%20%20%20%20%20%20%20%20onDateToChange%3D%7B(%7B%20value%20%7D)%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20setValueTo(value)%3B%0A%20%20%20%20%20%20%20%20%20%20%7D%7D%0A%20%20%20%20%20%20%20%20%20%20isPopover%3D%7Btrue%7D%0A%20%20%20%20%20%20%2F%3E%0A%20%20)%3B%0A%7D%0Arender(%0A%20%20%20%20%3CExample%20%2F%3E%0A)) неправильно работает

2021-06-28 13:44 UTC, reme3d2y commented on packages/calendar-range/src/useCalendarMonthes.ts
> +        : startOfMonth(inputValueFrom.date!).getTime();
У нас ! не подключен в сборке (работает только в сторибуке)
И ругается на no-negated-condition

2021-06-28 13:44 UTC, reme3d2y commented on packages/calendar-range/src/Component.tsx
> +    isPopover?: boolean;
Давай может для единообразия сделаем calendarPosition?: 'static' | 'popover';
А в коде можно уже сделать const isPopover = calendarPosition === 'popover';

2021-06-28 13:44 UTC, reme3d2y commented on packages/calendar-range/src/Component.tsx
> +import { useCalendarMonthes } from './useCalendarMonthes';
У нас автосортировки нет, но обычно весь css в самом конце импортим

2021-06-29 09:02 UTC, koretskyhub commented on packages/calendar-range/src/useCalendarMonthes.ts
> +        : startOfMonth(inputValueFrom.date!).getTime();
"!" убрал

2021-06-29 09:03 UTC, koretskyhub commented on packages/calendar-range/src/Component.tsx
> +    isPopover?: boolean;
сделал calendarPosition

2021-06-29 09:03 UTC, koretskyhub commented on packages/calendar-range/src/Component.tsx
> +import { useCalendarMonthes } from './useCalendarMonthes';
перенес

2021-06-29 09:04 UTC, koretskyhub commented
> Нужно бы тестов накинуть
> У меня вот такой [кейс](https://alfa-laboratory.github.io/core-components/86db70d22dc2f2f2fa1c38ffbaff3f6d665007c0/?path=/docs/%D0%B3%D0%B0%D0%B9%D0%B4%D0%BB%D0%B0%D0%B9%D0%BD%D1%8B-%D0%BF%D0%B5%D1%81%D0%BE%D1%87%D0%BD%D0%B8%D1%86%D0%B0--page/code=function%20Example()%20%7B%0A%20%20const%20defaultDate%20%3D%20%2230.06.2021%22%3B%0A%20%20const%20%5BvalueFrom%2C%20setValueFrom%5D%20%3D%20React.useState(defaultDate)%3B%0A%20%20const%20%5BvalueTo%2C%20setValueTo%5D%20%3D%20React.useState(%22%22)%3B%0A%20%20const%20minDate%20%3D%20(new%20Date().getTime())%20-%205%20*%2024%20*%2060%20*%2060%20*%201000%3B%0A%20%20const%20maxDate%20%3D%20(new%20Date().getTime())%20%2B%205%20*%2024%20*%2060%20*%2060%20*%201000%3B%0A%20%20%0A%20%20return%20(%0A%20%20%20%20%20%20%3CCalendarRange%0A%20%20%20%20%20%20%20%20%20%20minDate%3D%7BminDate%7D%0A%20%20%20%20%20%20%20%20%20%20maxDate%3D%7BmaxDate%7D%0A%20%20%20%20%20%20%20%20%20%20valueFrom%3D%7BvalueFrom%7D%0A%20%20%20%20%20%20%20%20%20%20valueTo%3D%7BvalueTo%7D%0A%20%20%20%20%20%20%20%20%20%20onDateFromChange%3D%7B(%7B%20value%20%7D)%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20setValueFrom(value)%3B%0A%20%20%20%20%20%20%20%20%20%20%7D%7D%0A%20%20%20%20%20%20%20%20%20%20onDateToChange%3D%7B(%7B%20value%20%7D)%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20setValueTo(value)%3B%0A%20%20%20%20%20%20%20%20%20%20%7D%7D%0A%20%20%20%20%20%20%20%20%20%20isPopover%3D%7Btrue%7D%0A%20%20%20%20%20%20%2F%3E%0A%20%20)%3B%0A%7D%0Arender(%0A%20%20%20%20%3CExample%20%2F%3E%0A)) неправильно работает

поправил этот кейс, добавил тестов на хук для max min дат

2021-06-30 06:20 UTC, reme3d2y approved these changes

2021-06-30 06:21 UTC, merged

2021-06-30 06:44 UTC, dmitrsavk commented
:tada: This PR is included in version 18.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@alfalab/core-components/v/18.2.0)
- [GitHub release](https://github.com/alfa-laboratory/core-components/releases/tag/v18.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: