fix(intl-phone-input): remove changing unclearable country code
alfa-laboratory/core-components pull request #730
Opened 2021-07-01 15:31 UTC by koretskyhub

ПРОДОЛЖАЕТ https://github.com/alfa-laboratory/core-components/pull/703

# Опишите проблему
Если каретка стоит до или внутри кода страны, пользователь начинает вводить символы, то каретка перемещается в конец кода страны

# Шаги для воспроизведения
- Открыть IntlPhoneInput
https://alfa-laboratory.github.io/core-components/master/?path=/story/%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B--intl-phone-input
Knob clearableCountryCode - false

- Поставить каретку внутри/до кода страны
- Ввести цифру

# Ожидаемое поведение
Если каретка стоит до или внутри кода страны и пользователь начинает вводить символы, то символы должны добавляться после кода страны

# Чек лист
- [ ] Тесты
- [ ] Документация

# Внешний вид

Ожидаемый        | Фактический
:---------------:|:--------------------|
** Ожидаемый  ** | ** Фактический    **|

# Тестовый стенд

## Десктоп (если данных нет оставте блок пустым):

## Смартфон (если данных нет оставте блок пустым):

# Дополнительная информация
Дополнительная информация

2021-07-02 04:55 UTC, reme3d2y commented
Я чет не увидел разницы. Плюс каретка после введенного символа прыгает в конец инпута

2021-07-05 08:24 UTC, koretskyhub commented
@reme3d2y, Конечно

Шаги для воспроизведения

перейти на страницу оплаты мобильной связи
кликнуть в поле ввода номера телефона
ввести цифру
кликнуть перед +7 (или между + и 7)
ввести цифру
Ожидаемый результат: цифра встанет между +7 и введенной цифрой ранее

Фактический результат: цифра заменяет +7 или встает между + и 7 

[было](https://alfa-laboratory.github.io/core-components/master/?path=/docs/%D0%B3%D0%B0%D0%B9%D0%B4%D0%BB%D0%B0%D0%B9%D0%BD%D1%8B-%D0%BF%D0%B5%D1%81%D0%BE%D1%87%D0%BD%D0%B8%D1%86%D0%B0--page/code=function%20Example()%20%7B%0A%20%20const%20%5Bvalue%2C%20setValue%5D%20%3D%20React.useState(%27%2B7%27)%3B%0A%20%20const%20handleChange%20%3D%20React.useCallback((newValue)%20%3D%3E%20%7B%20setValue(newValue)%3B%20%7D%2C%20%5BsetValue%5D)%3B%0A%0A%20%20return%20(%0A%20%20%20%20%20%20%3CIntlPhoneInput%20value%3D%7Bvalue%7D%20onChange%3D%7BhandleChange%7D%20clearableCountryCode%3D%7Bfalse%7D%20%2F%3E%0A%20%20)%3B%0A%7D%0Arender(%0A%20%20%20%20%3CExample%20%2F%3E%0A))

[стало](https://alfa-laboratory.github.io/core-components/3f2270a62d37a6228ae3ac22dc4e7a758d37c35e/?path=/docs/%D0%B3%D0%B0%D0%B9%D0%B4%D0%BB%D0%B0%D0%B9%D0%BD%D1%8B-%D0%BF%D0%B5%D1%81%D0%BE%D1%87%D0%BD%D0%B8%D1%86%D0%B0--page/code=function%20Example()%20%7B%0A%20%20const%20%5Bvalue%2C%20setValue%5D%20%3D%20React.useState(%27%2B7%27)%3B%0A%20%20const%20handleChange%20%3D%20React.useCallback((newValue)%20%3D%3E%20%7B%20setValue(newValue)%3B%20%7D%2C%20%5BsetValue%5D)%3B%0A%0A%20%20return%20(%0A%20%20%20%20%20%20%3CIntlPhoneInput%20value%3D%7Bvalue%7D%20onChange%3D%7BhandleChange%7D%20clearableCountryCode%3D%7Bfalse%7D%20%2F%3E%0A%20%20)%3B%0A%7D%0Arender(%0A%20%20%20%20%3CExample%20%2F%3E%0A))

2021-07-06 08:00 UTC, koretskyhub commented
Эта проблема актуальна, когда проп clearableCountryCode - false

Uploading Запись экрана 2021-07-06 в 10.48.15.mov…

2021-07-06 11:43 UTC, reme3d2y approved these changes

2021-07-06 11:45 UTC, reme3d2y requested changes
Вот такой кейс нашел

https://monosnap.com/file/1VX1vH61L1ZG7WqQFGWV6u6aU9F9cD

2021-07-08 07:30 UTC, koretskyhub commented
@reme3d2y fixed

2021-07-08 07:34 UTC, reme3d2y approved these changes

2021-07-08 07:41 UTC, reme3d2y commented
@koretskyhub 
Если ты уже погрузился в компонент — глянь плз сразу кейс, когда номер вставляется через 8 (например 89990312121). В обычном PhoneInput все ок, а тут нет

2021-07-08 07:45 UTC, AleksandrSerov commented
> Эта проблема актуальна, когда проп clearableCountryCode - false
> 
>  2021-07-06.10.48.15.mov

Хорошо бы, если бы каретка вставала не в конец инпута, а после введенного символа

2021-07-09 15:54 UTC, koretskyhub commented
@reme3d2y @AleksandrSerov done done

2021-07-12 13:12 UTC, AleksandrSerov commented on packages/intl-phone-input/src/utils/format-phone-with-unclearable-country-code.ts
> +const RUSSIAN_ALTERNATIVE_DIAL_CODE = '8';
В контексте libphonenumber-js это называется RUSSIAN_NATIONAL_DIAL_CODE

2021-07-12 14:23 UTC, koretskyhub commented on packages/intl-phone-input/src/utils/permit-caret-on-country-code.ts
> +    input.addEventListener('keyup', resetCaret);
да похоже

2021-07-13 15:38 UTC, koretskyhub commented
@AleksandrSerov, я убрал свдиг каретки на код страны по кнопке.
Поправить то же для мышкой кажется никак не выйдет. Слава в курсе, все окнул

2021-07-14 13:28 UTC, AleksandrSerov approved these changes

2021-07-14 15:39 UTC, reme3d2y approved these changes
Думаю этот ПР можно уже принять. 

Нам мой взгляд компонент еще стоит допилить, но это можно сделать отдельно и позже.

1. Не очень нравится, что блокируется каретка
2. Не нравится, что даже если страна уже определилась, все равно можно ввести лишние символы. К тому же в таком случае слетает форматирование.
3. В PhoneInput между цифрами дефисы. Стоит сделать консистентно везде

2021-07-14 15:39 UTC, reme3d2y commented on packages/intl-phone-input/src/useCaretAvoidCountryCode.ts
> +            const toLeftKey = event.keyCode === 37;
nit: можно на event.key заменить

2021-07-14 16:08 UTC, koretskyhub commented
> Думаю этот ПР можно уже принять.
> 
> Нам мой взгляд компонент еще стоит допилить, но это можно сделать отдельно и позже.
> 
> 1. Не очень нравится, что блокируется каретка
> 2. Не нравится, что даже если страна уже определилась, все равно можно ввести лишние символы. К тому же в таком случае слетает форматирование.
> 3. В PhoneInput между цифрами дефисы. Стоит сделать консистентно везде

Есть тасочка с еще одним кейсом для этого компонента, закину туда эти кейсы

2021-07-19 15:02 UTC, merged

2021-07-19 15:34 UTC, dmitrsavk commented
:tada: This PR is included in version 19.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@alfalab/core-components/v/19.2.0)
- [GitHub release](https://github.com/alfa-laboratory/core-components/releases/tag/v19.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: