feat(stepped-progress-bar): add component
alfa-laboratory/core-components pull request #747
Opened 2021-07-14 13:46 UTC by koretskyhub

## Добавляет - SteppedProgressBar
http://jira.moscow.alfaintra.net/browse/PDS-246

2021-07-14 15:31 UTC, reme3d2y requested changes

2021-07-14 15:31 UTC, reme3d2y commented on packages/stepped-progress-bar/src/Component.test.tsx
> +describe('SteppedProgressBar/Snapshots', () => {
Можешь оформить плз в общем стиле(глянь какой-нибудь другой компонент плз). Например снэпшот тесты сгруппировать в 
```
describe('Snapshots tests', ()
```

2021-07-14 15:31 UTC, reme3d2y commented on packages/stepped-progress-bar/src/Component.test.tsx
> +describe('SteppedProgressBar/Snapshots', () => {
По описаниям тестов непонятно, что должно вообще должно проверится. 
Не очень люблю снэпшоты — периодически их приходится обновлять и можно легко не заметить какой-то косяк.

Может заменить снэпшот-тесты на конкретные проверки?

2021-07-14 15:31 UTC, reme3d2y commented on packages/stepped-progress-bar/src/Component.test.tsx
> +describe('SteppedProgressBar/Snapshots', () => {
И давай лучше сразу сриншот-тестами покроем, в этом компоненте больше визуальную часть тестить нужно, чем разметку

2021-07-14 15:31 UTC, reme3d2y commented on packages/stepped-progress-bar/src/Component.tsx
> +    maxStep: number;
Нужны комменты для пропсов

2021-07-14 15:31 UTC, reme3d2y commented on packages/stepped-progress-bar/src/Component.tsx
> +import styles from './index.module.css';
```suggestion

import styles from './index.module.css';
```

2021-07-14 15:31 UTC, reme3d2y commented on packages/stepped-progress-bar/src/Component.tsx
> +                {Array.from(Array(validMaxSteps), (_, index) => (
Не знал, что в from есть колбэк)

2021-07-14 15:31 UTC, reme3d2y commented on packages/stepped-progress-bar/src/components/step-bar/Component.tsx
> +export const StepBar: FC<StepBarProps> = React.memo(({ isDone }) => (
nit: memo можно тоже достать из React, если уже FC импортнул

2021-07-14 15:31 UTC, reme3d2y commented on packages/stepped-progress-bar/src/docs/Component.stories.mdx
> +    parameters={{ 'theme-switcher': { themes: ['click'] } }}
Можно убрать

2021-07-14 15:31 UTC, reme3d2y commented on packages/stepped-progress-bar/src/docs/Component.stories.mdx
> +    <SteppedProgressBar step={number('step', 1)} maxStep={number('maxStep', 3)} description={text('description', "Шаг 1 из 3: Выбор карты")} />
Стоит добавить переносы

2021-07-14 15:31 UTC, reme3d2y commented on packages/stepped-progress-bar/src/docs/description.mdx
> +<Space fullWidth={true} direction='horizontal'>
Space не нужен же

2021-07-14 15:31 UTC, reme3d2y commented on packages/stepped-progress-bar/src/index.module.css
> +    flex-flow: row nowrap;
nit: можно убрать, т.к. это и так значение по умолчанию

2021-07-14 15:31 UTC, reme3d2y commented on packages/stepped-progress-bar/src/index.module.css
> +    display: flex;
nit: можно заменить на text-align: center для description

2021-07-15 13:19 UTC, koretskyhub commented on packages/stepped-progress-bar/src/Component.test.tsx
> +describe('SteppedProgressBar/Snapshots', () => {
я тут в целом хотел просто пройтись по граничным значениям и зафиксировать правильный вариант отрисовки
поменял снапшоты на скриншоты

2021-07-15 13:19 UTC, koretskyhub commented on packages/stepped-progress-bar/src/Component.tsx
> +    maxStep: number;
done

2021-07-15 13:19 UTC, koretskyhub commented on packages/stepped-progress-bar/src/Component.tsx
> +import styles from './index.module.css';
done

2021-07-15 13:19 UTC, koretskyhub commented on packages/stepped-progress-bar/src/components/step-bar/Component.tsx
> +export const StepBar: FC<StepBarProps> = React.memo(({ isDone }) => (
done

2021-07-15 13:19 UTC, koretskyhub commented on packages/stepped-progress-bar/src/docs/Component.stories.mdx
> +    parameters={{ 'theme-switcher': { themes: ['click'] } }}
done

2021-07-15 13:20 UTC, koretskyhub commented on packages/stepped-progress-bar/src/docs/Component.stories.mdx
> +    <SteppedProgressBar step={number('step', 1)} maxStep={number('maxStep', 3)} description={text('description', "Шаг 1 из 3: Выбор карты")} />
done

2021-07-15 13:20 UTC, koretskyhub commented on packages/stepped-progress-bar/src/docs/description.mdx
> +<Space fullWidth={true} direction='horizontal'>
done

2021-07-15 13:20 UTC, koretskyhub commented on packages/stepped-progress-bar/src/index.module.css
> +    flex-flow: row nowrap;
done

2021-07-15 13:20 UTC, koretskyhub commented on packages/stepped-progress-bar/src/index.module.css
> +    display: flex;
done

2021-07-15 13:42 UTC, reme3d2y commented on packages/stepped-progress-bar/src/index.module.css
> +    display: flex;
flex же тоже можно убрать

2021-07-15 13:43 UTC, reme3d2y commented on packages/stepped-progress-bar/src/Component.test.tsx
> +describe('SteppedProgressBar/Snapshots', () => {
Тесты все оставить, хотя бы базовые. Что mount\unmount работает, dataTestId и класс накидываются и т.д.
Можешь скопировать из другого компонента

2021-07-15 14:32 UTC, koretskyhub commented on packages/stepped-progress-bar/src/Component.test.tsx
> +describe('SteppedProgressBar/Snapshots', () => {
чет не нашел как в проекте тестируют маунт, а так done

2021-07-16 07:26 UTC, reme3d2y approved these changes

2021-07-19 14:09 UTC, aso1datov commented
nit: видел различные кейсы с таким прогресс-баром у мобайла, когда шаг может отличаться. Мб стоит уточнить у диза, не потребуется ли в дальнейшем подобная хотелочка и заложить ее?

![2021-07-19 17 08 44](https://user-images.githubusercontent.com/8918168/126173507-84f66456-cef7-45dd-83fe-b7bd4a61eeb5.jpg)

2021-07-19 15:17 UTC, reme3d2y commented
Ага, похоже вот эта строчка именно это и значит, но в макете это никак не отражено. Я начала тоже подумал только о зеленый\серый.

<img width="320" src="https://user-images.githubusercontent.com/9968618/126184194-a92ad011-e583-4614-a75b-b7592b693f0f.png" />


@koretskyhub уточнишь у диза?

2021-07-19 15:19 UTC, reme3d2y commented
И похоже description стоит сразу сделать функцией ({ step, maxStep }) => ReactNode

2021-07-20 15:42 UTC, SiebenSieben commented
Для текущей задачи достаточно того что есть. Потом доработаем если что. Антон посмотрел, дизайн-ревью ок.

2021-07-20 15:42 UTC, SiebenSieben approved these changes

2021-07-22 08:54 UTC, SiebenSieben commented
@koretskyhub нужно скрин поправить и будем мёрджить

2021-07-23 13:03 UTC, merged

2021-07-23 14:00 UTC, dmitrsavk commented
:tada: This PR is included in version 19.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@alfalab/core-components/v/19.3.0)
- [GitHub release](https://github.com/alfa-laboratory/core-components/releases/tag/v19.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: