fix(input): autofocus
alfa-laboratory/core-components pull request #761
Opened 2021-07-21 16:12 UTC by koretskyhub

В этом пр исправляется проблема лейбла наезжающего на картеку инпута с автофокусом.
Похоже вся проблема в том, что состояние фокуса хранится не только в доме но и в useFocus и в const [focused, setFocused] = useState(); Отсюда следует что оно может расходится. Что и происходит при монтировании <Input autoFocus />, стейт компонента в расфокусе а дом-нода в фокусе

2021-07-22 05:08 UTC, reme3d2y requested changes

2021-07-22 05:08 UTC, reme3d2y commented on packages/input/src/Component.tsx
> +            autoFocus,
Забыл прокинуть его дальше в инпут. Сейчас визуально фокус есть, но сам инпут не в фокусе

2021-07-22 05:08 UTC, reme3d2y commented on packages/input/src/Component.tsx
> +        let [focusVisible] = useFocus(inputRef, 'keyboard');
focusVisible — это если инпут выбран через таб. При автофокусе фокус происходит не с клавиатуры, поэтому рамка не нужна. Тем более автофокус не очень дружит с доступностью.
Поэтому можно focusVisible не трогать тут вообще

2021-07-22 05:08 UTC, reme3d2y commented
🔥

2021-07-23 04:51 UTC, reme3d2y approved these changes

2021-07-23 06:47 UTC, SiebenSieben approved these changes

2021-07-23 13:07 UTC, merged

2021-07-23 14:00 UTC, dmitrsavk commented
:tada: This PR is included in version 19.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@alfalab/core-components/v/19.3.0)
- [GitHub release](https://github.com/alfa-laboratory/core-components/releases/tag/v19.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: