Feat/add inactive controls
alfa-laboratory/core-components pull request #765
Opened 2021-07-23 13:38 UTC by koretskyhub

Добавляет inactive вариант для Switch, Checkbox, Radio
https://www.figma.com/file/uGndMZufgvqxaNQTaNTEjG/B2B-Web-Components?node-id=14238%3A111813

2021-07-26 05:23 UTC, reme3d2y requested changes

2021-07-26 05:23 UTC, reme3d2y commented on packages/checkbox/src/index.module.css
> -    --checkbox-checked-disabled-border-color: transparent;
Лучше не переименовывать переменные, это мажорно

2021-07-26 05:23 UTC, reme3d2y commented on packages/checkbox/src/index.module.css
> +    --checkbox-inactive-border-color: var(--color-dark-bg-secondary-inverted);
dark напрямую нигде не используем — в компонентах должны быть только light или static цвета. Замени на --color-light-border-secondary-inverted

2021-07-26 05:23 UTC, reme3d2y commented on packages/checkbox/src/index.module.css
> +    --checkbox-checked-muted-bg-color: var(--color-light-graphic-neutral);
Тут правильнее будет юзать --color-light-bg-neutral

2021-07-26 05:23 UTC, reme3d2y commented on packages/radio/src/index.module.css
> +    --radio-inactive-border-color: var(--color-dark-bg-secondary-inverted);
тут тоже

2021-07-26 05:23 UTC, reme3d2y commented on packages/radio/src/index.module.css
> +    --radio-checked-muted-bg-color: var(--color-light-graphic-neutral);
и тут

2021-07-26 05:23 UTC, reme3d2y commented on packages/switch/src/index.module.css
> +    --switch-inactive-color: var(--color-dark-bg-secondary-inverted);
и тут

2021-07-26 09:37 UTC, koretskyhub commented on packages/checkbox/src/index.module.css
> -    --checkbox-checked-disabled-border-color: transparent;
fixed

2021-07-26 09:37 UTC, koretskyhub commented on packages/checkbox/src/index.module.css
> +    --checkbox-inactive-border-color: var(--color-dark-bg-secondary-inverted);
fixed

2021-07-26 09:37 UTC, koretskyhub commented on packages/radio/src/index.module.css
> +    --radio-inactive-border-color: var(--color-dark-bg-secondary-inverted);
fixed

2021-07-26 09:37 UTC, koretskyhub commented on packages/radio/src/index.module.css
> +    --radio-checked-muted-bg-color: var(--color-light-graphic-neutral);
fixed

2021-07-26 09:38 UTC, koretskyhub commented on packages/switch/src/index.module.css
> +    --switch-inactive-color: var(--color-dark-bg-secondary-inverted);
fixed

2021-07-26 09:41 UTC, koretskyhub commented on packages/checkbox/src/index.module.css
> +    --checkbox-checked-muted-bg-color: var(--color-light-graphic-neutral);
fixed

2021-07-26 10:26 UTC, reme3d2y reviewed
Закинь еще скриншот-тесты плз. И тест на то, что если юзается inactive, то инпуты блокируются

2021-07-26 11:53 UTC, reme3d2y approved these changes

2021-08-03 05:32 UTC, merged

2021-08-03 06:05 UTC, dmitrsavk commented
:tada: This PR is included in version 19.4.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@alfalab/core-components/v/19.4.0)
- [GitHub release](https://github.com/alfa-laboratory/core-components/releases/tag/v19.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: