Feat/chart
alfa-laboratory/core-components pull request #835
Opened 2021-09-14 05:44 UTC by SNosenko

Компонент для построения графиков

2021-09-27 05:46 UTC, reme3d2y requested changes

2021-09-27 05:46 UTC, reme3d2y commented on packages/chart/src/Component.tsx
> +import LinearGradient from './components/LinearGradient';
Мы стараемся не юзать дефолтные экспорты

2021-09-27 05:46 UTC, reme3d2y commented on packages/chart/src/Component.tsx
> +        if (!state) return null;
Стоит тут и ниже добавить отступы между смысловыми блоками, чтобы код легче читался

2021-09-27 05:46 UTC, reme3d2y commented on packages/chart/src/Component.tsx
> +            if (charts[`${dataKey}`] && filterCount > 1) {
```suggestion
            if (charts[dataKey] && filterCount > 1) {
```

2021-09-27 05:46 UTC, reme3d2y commented on packages/chart/src/Component.tsx
> +                const h = node.getBoundingClientRect().height;
Кажется, что тут смысла от переменной нет. Либо стоит сделать { height }

2021-09-27 05:46 UTC, reme3d2y commented on packages/chart/src/Component.tsx
> +    const CustomLegend = useCallback(
Стоит перенести в renderLegend
CustomLegendProps можно дропнуть

2021-09-27 05:46 UTC, reme3d2y commented on packages/chart/src/Component.tsx
> +                    transform: `translateY(${
тяжело читается

2021-09-27 05:46 UTC, reme3d2y commented on packages/chart/src/Component.tsx
> +                                  // SvgIcon: properties.dot, // Возможность передать кастомную иконку, статус: Доработать
Если это прям сейчас не планируешь, то лучше убрать коммент. или пометить TODO:

2021-09-27 05:46 UTC, reme3d2y commented on packages/chart/src/Component.tsx
> +    const RenderLine = useCallback(
Это ведь не компонент, поэтому стоит в маленькой буквы писать.

2021-09-27 05:46 UTC, reme3d2y commented on packages/chart/src/Component.tsx
> +    const RenderBar = useCallback(
А почему эти Render* не сделал отдельными компонентами?

2021-09-27 05:46 UTC, reme3d2y commented on packages/chart/src/Component.tsx
> +                    {data.map((entry: DataDynamicProps, index: number) => {
```suggestion
                    {data.map((_: DataDynamicProps, index: number) => {
```

2021-09-27 05:46 UTC, reme3d2y commented on packages/chart/src/Component.tsx
> +                                    typeof activeDotsState.active === 'number' &&
Кажется, что это лишняя проверка тут

2021-09-27 05:46 UTC, reme3d2y commented on packages/chart/src/Component.tsx
> +                properties = {},
лишнее?

2021-09-27 05:46 UTC, reme3d2y commented on packages/chart/src/Component.tsx
> +            if (state) {
nit:
```suggestion
            if (!state) return null
```

2021-09-27 05:46 UTC, reme3d2y commented on packages/chart/src/Component.tsx
> +    }, [state, CustomLegend]);
Меня немного смущает, что везде в зависимости попадает state. Сейчас от мемоизации больше минусов, т.к. инвалидация будет на каждый чих

2021-09-27 05:46 UTC, reme3d2y commented on packages/chart/src/Component.tsx
> +        const marginTick = state?.xAxis?.tickMargin ? state?.xAxis?.tickMargin : 0;
отступы плз))

2021-09-27 05:46 UTC, reme3d2y commented on packages/chart/src/Component.tsx
> +    useEffect(() => {
options, settings и state — должен остаться кто-то один))

Кажется, что у компонента должно быть много пропсов, а внутри ты можешь сделать settings или options уже

Еще момент — почему это в юзеффект? Нельзя ли вынести генерацию настроек в отдельный файл, а в компоненте заюзать через useMemo?

2021-09-27 05:46 UTC, reme3d2y commented on packages/chart/src/Component.tsx
> +        if (!isTooltipActive) {
Стоит развернуть условие

2021-09-27 05:46 UTC, reme3d2y commented on packages/chart/src/Component.tsx
> +                (svgRef.current?.clientWidth ? svgRef.current?.clientWidth : 0) -
сложно читать

2021-09-27 05:46 UTC, reme3d2y commented on packages/chart/src/Component.tsx
> +            const next = {
зачем отдельные переменные?

2021-09-27 05:46 UTC, reme3d2y commented on packages/chart/src/Component.tsx
> +            typeof activeDotsState.active === 'number' &&
кажется проверка лишняя

2021-09-27 05:46 UTC, reme3d2y commented on packages/chart/src/components/Dot/index.module.css
> +.dotUnfocused {
префикс делать не нужно, т.к. все эти стили только для компонента Dot

2021-09-27 05:46 UTC, reme3d2y commented on packages/chart/src/components/Dot/index.tsx
> +    const { cx, cy, index, activeDot, dataKey, dotSettings } = props;
Мы обычно это делаем в объявлении компонента

2021-09-27 05:46 UTC, reme3d2y commented on packages/chart/src/components/Dot/index.tsx
> +        let dotSetting: DotSettingProps =
выглядит сложновато

2021-09-27 05:46 UTC, reme3d2y commented on packages/chart/src/components/Legends/index.tsx
> +// icons
Коммент стоит убрать, суффикс icon из названий файлов тоже

2021-09-27 05:46 UTC, reme3d2y commented on packages/chart/src/components/Legends/index.tsx
> +        const getIcon = (type: string) => {
nit: можно вынести за компонент и заменить на словарь

2021-09-27 05:46 UTC, reme3d2y commented on packages/chart/src/components/Legends/index.tsx
> +const Legends = React.forwardRef<HTMLUListElement, LegendComponentProps>(
```suggestion
const Legends = React.forwardRef<HTMLUListElement, LegendsProps>(
```

2021-09-27 05:46 UTC, reme3d2y commented on packages/chart/src/components/LinearGradient.tsx
> +                const key = `${id}${gid}-${index}`;
лишняя переменная

2021-09-27 05:46 UTC, reme3d2y commented on packages/chart/src/components/Tick/index.module.css
> +    font-size: 16px;
nit: можно миксин заюзать

2021-09-27 05:46 UTC, reme3d2y commented on packages/chart/src/components/Tick/index.tsx
> +            <text className={cn(styles.tickText)} y='15' dy='0.71em'>
0.71em — magic number. Стоит коммент оставить, почему так

2021-09-27 05:46 UTC, reme3d2y commented on packages/chart/src/components/Tick/index.tsx
> +            <circle r={radius} fill='#0B1F35' opacity='0.3' />
в css не получится вынести цвет?

2021-09-27 05:46 UTC, reme3d2y commented on packages/chart/src/components/Legends/index.module.css
> +@import '../../../../vars/src/index.css';
Нужно из themes подключать

2021-09-27 05:46 UTC, reme3d2y commented on packages/chart/src/types/brush.type.ts
> +    /**
Комменты стоит разделить отступами

2021-09-27 05:46 UTC, reme3d2y commented on packages/chart/src/types/utils/tick.type.ts
> +    xAxis: XAxisProps;
коммент

2021-09-28 07:27 UTC, dmitrsavk commented on packages/chart/package.json
> +{
`package-lock.json` лишний, мы же `yarn` используем, лучше удалить)

2021-09-28 07:27 UTC, dmitrsavk commented on packages/chart/src/Component.tsx
> +    const renderChartsItems = useMemo(() => {
Может попробовать это вынести в отдельный компонент? А то сейчас очень громоздко выглядит

2021-09-28 07:27 UTC, dmitrsavk commented on packages/chart/src/Component.tsx
> +    useEffect(() => {
Эту функцию нужно обязательно вынести в отдельный файл. Возможно можно сделать кастомный хук.
Плюс к этому, ее еще нужно разбить на 5-6 отдельных функций.

2021-09-28 07:34 UTC, SNosenko commented on packages/chart/src/Component.tsx
> +            if (charts[`${dataKey}`] && filterCount > 1) {
Здесь dataKey может быть числом и строкой

2021-09-30 14:11 UTC, reme3d2y approved these changes

2021-09-30 14:14 UTC, dmitrsavk approved these changes

2021-09-30 14:14 UTC, merged

2021-09-30 14:41 UTC, dmitrsavk commented
:tada: This PR is included in version 20.4.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@alfalab/core-components/v/20.4.0)
- [GitHub release](https://github.com/alfa-laboratory/core-components/releases/tag/v20.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: