feat(button): добавлена кнопка размера 40px, изменены скругления
alfa-laboratory/core-components pull request #886
Opened 2021-11-15 11:09 UTC by dmitrsavk

- [ ] Button
- [ ] Tag
- [ ] Deprecate some button views

2021-11-17 06:44 UTC, EGNKupava approved these changes

2021-11-19 09:07 UTC, Oladii approved these changes

2021-11-22 06:12 UTC, reme3d2y approved these changes

2021-11-22 07:30 UTC, SiebenSieben commented
Надо проверить, чтобы в темах click/corp кнопочки остались как раньше (цвета/скругления).

И в канальчик написать про изменения и кодмод.

И тогда смёрджим 🚀

2021-11-22 07:39 UTC, Oladii requested changes
В кнопках прессед стейты разъехались. В темах сайта и дефолта должны быть идентичные.  Нужно на дефолтных сделать такой же эффект уменьшения при тапе, как сейчас у сайта.

2021-11-23 06:17 UTC, SiebenSieben approved these changes

2021-11-23 07:48 UTC, Oladii approved these changes

2021-11-26 09:10 UTC, merged

2021-11-26 09:40 UTC, dmitrsavk commented
:tada: This PR is included in version 22.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@alfalab/core-components/v/22.0.0)
- [GitHub release](https://github.com/alfa-laboratory/core-components/releases/tag/v22.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: