feat(file-upload-item): обновлен внешний вид
alfa-laboratory/core-components pull request #902
Opened 2021-11-29 11:56 UTC by dmitrsavk

http://jira.moscow.alfaintra.net/browse/PDS-294

2021-11-29 13:14 UTC, reme3d2y approved these changes

2021-12-01 13:51 UTC, Oladii requested changes
Визуально отступ в правой части между размером файла и датой не соответствуют макету.
У блока "размер файла" в верстке фиксированный размер, из за этого при коротком значении 43.95MB появляется дополнительный отступ слева. Решение -> cделать размер блока гибким.

2021-12-08 14:30 UTC, Oladii approved these changes

2021-12-09 13:00 UTC, merged

2021-12-09 13:27 UTC, dmitrsavk commented
:tada: This PR is included in version 23.1.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@alfalab/core-components/v/23.1.0)
- [GitHub release](https://github.com/alfa-laboratory/core-components/releases/tag/v23.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: